### PR TITLE
Point to new location for pip

### PR DESCRIPTION
**Pull request by hellais**

### CODE REVIEW

**Comment by SuperQ** [comment]
Why not use an apt package install of python-pip?

**Comment by hellais** [comment]
Because the dockerfile that is using this ansible role is based on debian wheezy, that has an older version of pip (1.1) that doesn't do certificate validation when fetching HTTPS dependencies :(.

I guess that since the latest stable of debian now ships with a decent version of pip, we could update the Dockerfile and use python-pip instead.

**Comment by SuperQ** [comment]
:crying_cat_face:

**Comment by anadahz** [comment]
This has been fixed in #38

**Comment by anadahz** [comment]
This is still needed my bad.
Merging!

**Pull request merged**
