### PR TITLE
Add roles for spinning up VMs on eclipsis

### PR DESCRIPTION
**Pull request by hellais**
This is the playbook I use to spin up VMs on eclipsis with support for travis automatic deployment.

I run it like this:

```
DO_API_TOKEN="XXXX" ~/.virtualenvs/ooni-sysadmin/bin/ansible-playbook -i eclipsis-inventory --extra-vars "instance_name=SOMETHING_UNIQUE" --extra-vars "disk_size=40" ansible/provision-staging-vm.yml
```

And `eclipsis-inventory` contains something like this:

```
[local]
localhost ansible_connection=local
[eclipsis_hosts]
[eclipsis_hosts:vars]
ansible_ssh_private_key_file=/path/to/private-key-for-eclipsis
```

Also look at the comment inside of the playbook for more instructions.

### CODE REVIEW

**Comment by anadahz** [comment]
How are you installing ansible in order to use this role?
There is a dependency required (module pycompat24) (https://github.com/TheTorProject/ooni-sysadmin/pull/76/files#diff-449ad293871a4bb773e2d84d3f805239R11).

```
task path: ~/ooni-sysadmin/ansible/provision-staging-vm.yml:56
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Could not find imported
module support code for eclipsis_droplet.  Looked for either get_exception or
pycompat24"}
```
`# ansible --version`
```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
    configured module search path = Default w/o overrides
```

**Comment by hellais** [comment]
> How are you installing ansible in order to use this role?

I have ansible setup inside of a virtualenv with the version of ansible that is recent enough. Are you sure that version of ansible (2.1.1) is the one being used when you run `ansible-playbook`?

**Comment by anadahz** [comment]
OK it seems that ansible version 2.2.0 is needed to use the `eclipsis_droplet` library.
I guess this should be updated: https://github.com/TheTorProject/ooni-sysadmin/pull/76/files#diff-449ad293871a4bb773e2d84d3f805239R6

**Comment by hellais** [comment]
Is this PR useful? Can we merge it or ... ?

**Comment by anadahz** [comment]
Last time I tested it locked the eclipsis account.
I guess this may be resolved by now as eclipsis has been upgraded multiple times since then.

**Comment by darkk** [comment]
@hellais is this PR useful? :-)
I mean, do you use it as a part of some workflow?

**Comment by hellais** [comment]
> @hellais is this PR useful? :-)

it could be if eclipsis stabilises their API and starts supporting it officially.

> I mean, do you use it as a part of some workflow?

not currently, because of instabilities in the eclipsis API, but it could be useful to start using it for automating the creation and destruction of VMs.

**Comment by hellais** [comment]
I made an offline copy of this in `development/eclipsis-ansible`, closing this as no longer relevant.

**Pull request closed without merging**
