### PR TITLE
munin monitoring work

### PR DESCRIPTION
**Pull request by joelanders**
https://trac.torproject.org/projects/tor/ticket/13583

*number of reports in each aggregator-pipeline-state
** can write a plugin to do this
*is HS up?
** ditto ^
*disk usage
** done
*memory usage
** done
*cpu usage
** done
*process monitoring
** done
*in/out network bandwidth usage
** done

### CODE REVIEW

**Comment by hellais** [comment]
Seems promising. @andaraz @bassosimone

**Comment by hellais** [comment]
The quality of this code is very good. It's very old-skewl like I :heart: it.

I am going to proceed and merge it, thanks @joelanders!

**Comment by anadahz** [comment]
@joelanders nice work!
How can I test this? Is there a doc or something similar?

**Comment by joelanders** [comment]
@anadahz hm, testing is a good question. I'm not sure what kind of play-testing things Ansible provides.

I've just been running it against EC2 and SSHing over to check the config files are correct, and hitting the nginx-served graphs to see that part is working :)

**Comment by anadahz** [comment]
@joelanders could we use this role without using EC2 and AWS services or AWS is a hard requirement?

**Comment by joelanders** [comment]
Yeah, the munin_master and munin_slave roles ought to work on any host.

**Comment by anadahz** [comment]
hi @joelanders 
I would like to monitor some lepidopter RasPi hosts do we have any update on this?

**Pull request merged**
