### PR TITLE
Update ooniprobe role to install ooniprobe v2

### PR DESCRIPTION
**Pull request by anadahz**
* Install ooniprobe v2 via pip and run ooniprobe-agent as a service with
systemd.
* Improve installation of tor GPG key
* Update documentation

### CODE REVIEW

**Comment by darkk** [comment]
@hellais @anadahz is this code still useful?

`ooniprobe` role is deployed to `local:custom` set of nodes that are not found in the `inventory`.

**Comment by anadahz** [comment]
> @hellais @anadahz is this code still useful?

This role has been used to deploy ooniprobe in Debian like systems.
It's not part of the infrastructure though used to be useful to deploy ooniprobe via ansible.

> ooniprobe role is deployed to local:custom set of nodes that are not found in the inventory.

The inventory groups have changed significantly since then.
The `custom` group name was used as a set of custom nodes defind by the user.

**Comment by hellais** [comment]
@anadahz can we drop this PR? I would drop it since it's not really working anymore properly.

**Comment by anadahz** [comment]
Indeed let's drop this PR.

**Pull request closed without merging**
