### PR TITLE
More shell script work and sketch out *Master Ansible Deploy Playbook*

### PR DESCRIPTION
**Pull request by joelanders**
Don't worry about the nasty diff, just look at my tree:

```
landers@tp25 ~/c/T/o/ooni-sysadmin-ng> tree
.
├── master-deploy-playbook.yaml
├── ooni-api
│   ├── _datasources.production.js.sh
│   ├── install-ooni-api.sh
│   └── _ooni-api.service.sh
├── ooni-backend
│   ├── install-ooni-backend.sh
│   ├── _install-packages.sh
│   ├── _oonibackend.conf.sh
│   ├── _oonibackend.service.sh
│   ├── README.md
│   ├── _torproject-rpm-key.asc
│   └── _tor.repo
├── ooni-pipeline
│   ├── install-ooni-pipeline-emr.sh
│   ├── install-ooni-pipeline.sh
│   └── _invoke.yaml.sh
├── ooni-probe
│   ├── install-ooniprobe-bridge-reachability.sh
│   ├── _ooniprobe-bridge-run.service.sh
│   ├── _ooniprobe-bridge-run.timer
│   ├── _ooniprobe-bridges.txt
│   └── _ooniprobe.conf.sh
└── ooni-puppet-master
    └── install-ooni-puppet-master.sh
```

And read the `master-deploy-playbook.yaml` for my thoughts on sticking a nice (and simple) Ansible entry-point on top of all of this.

### CODE REVIEW

**Comment by joelanders** [comment]
god i hate computers, this takes forever to develop.
this will provision an ec2, copy the scripts, and install everything except the requirements.txt stuff for some reason i will figure out tomorrow.

**Comment by joelanders** [comment]
this commit was pure pain.
the virtualenvwrapper.sh tests for uninitialized variables in a way that makes `set -u` unhappy and kills the script.
then I misspelled `$ooni_password` as `$ooni_pass` which also made `set -u` unhappy, but the reason didn't get bubbled all the way back out the ansible output, so it took forever to find.
i hate computers.

**Comment by joelanders** [comment]
oh but it will install everything.
at this point, you can ssh in, `workon ooni-pipeline`, `cd ooni-pipeline`, `invoke whatever` and it should work.

next we want to be able to specify an invoke command without sshing in and stuff.

**Comment by anadahz** [comment]
@joelanders is this ready to be tested?

**Comment by anadahz** [comment]
I'm a bit lost here, @joelanders , @hellais can you shed some light here?

**Comment by hellais** [comment]
I think a lot of this is no longer relevant since it's pertaining to EC2 based deployments. Some stuff is in the form of shell scripts, but it should actually be in the form of ansible roles.

Perhaps the best way forward is to merge this and put in attic and make a ticket about converting the shell scripts for the ooni-api deployment into ansible?

**Comment by joelanders** [comment]
:grimacing: yikes, I'm in a bad mood up there...

My idea was to do the per-machine stuff in shell scripts (like `install-ooni-backend.sh` and `install-ooni-pipeline.sh` (the ones beginning with underscore are called from the `install-*.sh` ones)).

The Ansible playbook here does
* the EC2 provisioning (make sure an instance with tag, eg, `role:ooni-backend` is running
* populate the inventory with the instance found or the instance newly started
* copy over the appropriate shell scripts
* run the shell scripts

I found the shell scripts easier to develop with (can just SSH and copy/paste commands to debug), less verbose, and maybe more useful to other people (READMEs tend to contain installation instructions in bash). But I wanted Ansible to do the role/inventory stuff and give us a nice command to run from a developer laptop.

Maybe I'm the only one who finds Ansible's YAML stuff hella ugly, so whatever.

The shell scripts shouldn't be EC2-specific, but there's probably a lot of other stuff that changed in the last 6 months.

**Comment by SuperQ** [comment]
I agree with @hellais, it's best to use ansible functionality when possible and avoid shell scripts.  Yes the YAML stuff can be a bit ugly, but it provides a more structured and automatic workflow.  For example adding an apt repo automatically deals with `apt-get update`.

**Comment by joelanders** [comment]
Y'all are probably right, then, and I humbly concede the point!

**Comment by joelanders** [comment]
@SuperQ Have you seen this [Rancher](http://rancher.com/) thing?

It's like a layer on top of Kubernetes/Swarm/Mesos.

hosts

**Comment by SuperQ** [comment]
Yea, I looked at it briefly.  It wasn't interesting for our stuff at work
because we already have everything it does.  But maybe useful for ooni.

**Comment by darkk** [comment]
@joelanders @hellais @anadahz is there anything in this branch that is still useful?

**Comment by joelanders** [comment]
@darkk Probably not, I was trying to do most stuff with shell scripts (for debuggability and README/INSTALL reusability), and I think it's massively out-of-date by now, anyway. Feel free to delete it.

**Comment by hellais** [comment]
I am going to close this.

**Pull request closed without merging**
