### PR TITLE
Replace testing notification certificate with dev certificate

### PR DESCRIPTION
**Pull request by hellais**
In this PR I change the certificate used by the testing notification server (notify.proteus.test.ooni.io).

I haven't deployed it yet, because in order to deploy this I will also have to reset the database, so I would like to first get the green light on this from @bassosimone at least.

Next steps to deploy this:

* [ ] Get green light that it's OK to reset the testing database
* [ ] Reset the testing database
* [ ] Deploy this update

@lorenzoPrimi what happens to old test flight users? Will they have to do some special action to get their app to start working again?

In the email you sent me it says:
> Before overwriting an app from TestFlight with another from Xcode or viceversa, uninstall the old one. The new app will have a different token and we dont want any conflict

But I don't fully understand what this means.

### CODE REVIEW

**Comment by hellais** [comment]
@darkk any idea why the inventory check is failing? I didn't make any changes to the inventory.

**Comment by lorenzoPrimi** [comment]
It means that if you (or @bassosimone ) have and app installed through TestFlight and want to deploy an app from XCode to the device (or viceversa) you must uninstall the old app before.

To me more clear:
TestFlight : uses proteus and prod certificate
Deploy with XCode to the device: uses proteus dev and dev certificate

**Comment by hellais** [comment]
> It means that if you (or @bassosimone ) have and app installed through TestFlight and want to deploy an app from XCode to the device (or viceversa) you must uninstall the old app before.

Gotcha. So this does not affect existing test flight users that don't plan to deploy the app from Xcode?

**Comment by lorenzoPrimi** [comment]
Only me you and Simone can deploy the app from XCode to our phones using the dev certificate we have

**Comment by darkk** [comment]
@hellais inventory check is failing as I've left it in inconsistent state yesterday after merging some deployed-but-not-merged PRs

**Comment by hellais** [comment]
> inventory check is failing as I've left it in inconsistent state yesterday after merging some deployed-but-not-merged PRs

Could you fix it and merge it into this branch?

**Comment by hellais** [comment]
@lorenzoPrimi is this still needed? Should we merge it and deploy it or not?

**Comment by lorenzoPrimi** [comment]
notify.proteus.test.ooni.io is not used at all at the moment. We will probably need it again when we will implement orchestration to test it on a dev environment.

**Comment by hellais** [comment]
Ok I am going to close this then.

**Pull request closed without merging**
