### PR TITLE
Add ansible tasks to setup and control docker SYSv init scripts

### PR DESCRIPTION
**Pull request by anadahz**
Tasks:
* Setup docker SYSV init.d script
* Enable docker SYSV init.d script
* Start docker SYSV init.d script
* Restart docker SYSV init.d script
* Stop docker SYSV init.d script

Template:
Add docker SYSV init.d script

### CODE REVIEW

**Comment by hellais** [comment]
I think we are going to proceed in the meantime to a non docker solution since on non bare metal machines it's easier to just spin up a new VM than it is to run docker.

I am nonetheless not going to close this as it's very useful stuff. Thanks for working on it :+1:

**Comment by anadahz** [comment]
SYSV  init scripts were most useful to older Debian releases (i.e wheezy).
I guess we should close this PR.
@hellais  do we have a git-grave for all these possibly useful commits?

**Comment by hellais** [comment]
I am not sure what a git-grave is, but as long as you don't delete the branch it stays here.

**Comment by anadahz** [comment]
@hellais git-grave, a place potentially useful things can be stored "forever" :)

**Pull request closed without merging**
