### PR TITLE
Feature/ansible install ooniprobe

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by hellais** [comment]
Can you rebase this against master?

**Comment by anadahz** [comment]
Try again. @hellais

**Comment by hellais** [comment]
As highlighted in the other PR too, you need to squash them on top of master and not re-create new commits.

**Comment by anadahz** [comment]
@hellais is it OK now?

**Comment by hellais** [comment]
Yes now it looks good. I will tend to this in the upcoming days.

**Comment by hellais** [comment]
Actually since @joelanders is working on this already I will task him to review this.

**Comment by joelanders** [comment]
@anadahz Heh, I think PR #14 conflicted with this one; can you rebase once more?

**Comment by anadahz** [comment]
@joelanders done.

**Comment by joelanders** [comment]
Alles gute!

**Pull request merged**
