### PR TITLE
[WIP] Add Prometheus monitoring server

### PR DESCRIPTION
**Pull request by SuperQ**
Add a role for installing a Prometheus monitoring server.

### CODE REVIEW

**Comment by hellais** [comment]
This looks great, thanks for putting it together!

Would it be possible to also add some examples on how we would go abouts adding exporters to one of our components?

I think for the moment the most high priority things to monitor is probably [ooni-backend](https://github.com/TheTorProject/ooni-sysadmin/tree/master/ansible/roles/ooni-backend). What we would like to be able to monitor there is:
* Basic machine metrics (with node_exporter)
* Something to monitor if the actual ooni-backend collector (a HTTP(s) service) is running properly (it runs inside of docker) either via a process monitor or by reaching the HTTP(s) endpoints

**Comment by SuperQ** [comment]
Sure, exporter/metrics examples are pretty easy.  I wanted to start with the server side.

For monitoring nodes, we will need to enumerate all of the nodes, this is easy to do with ansible's host inventory.

For monitoring jobs, we will need to enumerate all of the instances of the app running in docker.  If this is also in some kind of ansible inventory, it should be easy to do.

As for how to get the data out of the ooni-backend, it will be best to integrate one of the Prometheus application libraries[0].

[0]: https://prometheus.io/docs/instrumenting/clientlibs/

**Comment by hellais** [comment]
Note: this is superseeded by #108

**Comment by darkk** [comment]
@SuperQ thanks a lot for helping to bootstrap that

**Pull request closed without merging**
