### PR TITLE
Introduce Travis CI tests for OONI docker builds

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by anadahz** [comment]
@hellais this requires travis-ci to be enabled on this repository. To enable travis on a repository admin rights are needed

**Comment by hellais** [comment]
Travis enabled 👍

**Comment by anadahz** [comment]
Fixes for docker images:
#40, #35, #41

**Comment by hellais** [comment]
The docker image seems to be built properly. It's just the script itself is failing to run.

**Comment by hellais** [comment]
What should be done of this?

**Comment by anadahz** [comment]
> What should be done of this?

Since we are doing the testing and CI in the software repositories, it makes more sense to disable Travis tests in ooni-sysadmin repository.

We can always re-enable Travis when we have a clear plan of what we would like to test.

**Comment by darkk** [comment]
Closing, as it's tagged **[invalid]** long long ago.

**Pull request closed without merging**
