### PR TITLE
Feature/ooni backend setup role

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by hellais** [comment]
Somehow I had missed this code. Could you please rebase it against master and I shall review it.

Thanks!

**Comment by anadahz** [comment]
OK please check!

**Comment by hellais** [comment]
Almost there, though you need to clean up the commit history so that the rebased commits are squashed and not on top of the old ones.

**Comment by anadahz** [comment]
@hellais please recheck, thanks.

**Comment by joelanders** [comment]
Looks good.

**Pull request merged**
